### ISSUE TITLE
Change min zoom limit in web map

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis.com-webgis#15]
Min zoom limits now are 4. The min zoom 3 (as in google maps) will be enough.

**Comment by kalenkov** [comment]
Да, четвертого зума мало. Россия не влезает.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/acbd305b712722e49bb6315cc59980ee88e9820d
