### ISSUE TITLE
Размер карточки Идентификация

### ISSUE THREAD

**Issue by kalenkov** [nextgis/nextgis.com-webgis#16]
Размер карточки "Идентификация" никак изменить нельзя или я не нашел такой возможности. Иногда инстинктивно потянуть её за уголок, чтобы сделать побольше.

**Comment by Solski** [comment]
Да, у меня не видно половины атрибутов: 
![screenshot - 28_12](https://cloud.githubusercontent.com/assets/19263119/21522415/9f6be838-cd05-11e6-9535-9ba014e413ae.png)

**Comment by simgislab** [comment]
используйте алиасы 
или следите за https://github.com/nextgis/nextgisweb/issues/544

**Comment by simgislab** [comment]
Размер окна идентификация теперь можно настраивать через Панель управления - Настройки Веб карт
