### ISSUE TITLE
Рендеринг на дальнем востоке

### ISSUE THREAD

**Issue by kalenkov** [nextgis/nextgis.com-webgis#17]
Иногда странно себя ведет отрисовка на дальнем востоке. Часто вижу вот такую картину
![18-1](https://cloud.githubusercontent.com/assets/8274001/16530534/a108f4b0-3fd9-11e6-89dd-3d60bb7e51e4.png)
http://duma2016.nextgis.com/resource/1/display?base=osm-mapnik&lon=146.4803&lat=54.4987&angle=0&zoom=4&styles=15,17,19,21,23
Если подергать зумом, то рано или поздно всё встает на свои места.

**Comment by kalenkov** [comment]
Поправка. На четвертом зуме сдвиг не пропадает, чтобы я не делал.

**Comment by ABiatov** [comment]
на этой карте не только на Дальнем Востоке сдвиг.
http://duma2016.nextgis.com/resource/1/display?base=osm-mapnik&lon=111.2526&lat=64.2428&angle=0&zoom=3&styles=30,34,32,33,31
![screenshot-11122016-05_31_25 pm](https://cloud.githubusercontent.com/assets/13443276/20238913/0d958656-a8fe-11e6-8855-622cedc0e0cd.png)

**Comment by kalenkov** [comment]
да, сдвигает весь слой. Но такое наблюдается только в том случае, если в пределы карты попадает Дальний Восток. Если смотреть только европейскую часть, то сдвига нету. Поэтому я полагаю, что это вызвано проблемами на сервере, а не ошибками в исходных данных.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb_qgis/commit/077b7e799478f4c059049230fa8421882a7b06c8
