### ISSUE TITLE
API results in 502 with PUT and DELETE

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis.com-webgis#2]
_From @trolleway on May 23, 2016 15:18_

Запросы наподобие этого

PUT
http://trolleway.nextgis.com/api/resource/35/feature/7

```
'{"fields": {"show_label": 1, "angle": 141.053495, "road_id": 7, "always_show": "", "y": 7533286.170419, "x": 4187328.194437, "routes_ref": "309>", "rotation": "", "alignment": ""}, "geom": "LINESTRING (4187063.94 7533556.81,4187125.5 7533515.91,4187185.88 7533462.25,4187532.55 7533033.33,4187567.65 7532989.71)"}'
```

выдают ошибку 502

_Copied from original issue: nextgis/nextgis.com#35_

**Comment by simgislab** [comment]
авторизован?

**Comment by simgislab** [comment]
_From @trolleway on May 24, 2016 10:0_

Да, проверял через REST client, с авторизацией

**Comment by drnextgis** [comment]
Сейчас нет такого ресурса, нужно либо сделать воспроизводимый пример, либо закрываем.

**Comment by simgislab** [comment]
@trolleway проверь еще раз и давай пример

**Comment by trolleway** [comment]
Пока не могу воспроизвести, потому что обновил Ubuntu, и всё поломалось.

**Comment by trolleway** [comment]
У меня воспроизводится: PUT выдаёт 502 ошибку. 

```
import requests
req = requests.put('http://trolleway.nextgis.com/api/resource/53/feature/12', data={ "fields": {"line_id": 1, "name": ""}, "geom": "LINESTRING (1000000.8 3333848.66935069,1500000.83806583 976031.089522025)"}, auth=('debugger','debugger'))
print 'status code:'+str(req)
```

**Comment by BishopGIS** [comment]
Оказывается поле extensions обязательное. Подправлю доки.

  curl 'http://trolleway.nextgis.com/api/resource/53/feature/12' -X PUT -H 'Content-Type: application/json' --data '{"fields":{"name":"","line_id":1},"extensions":{"description":""}}' --user debugger:debugger

**Comment by dezhin** [comment]
Не надо, это же очевидно баг.

**Comment by BishopGIS** [comment]
ок, доки не трогаю.

**Comment by drnextgis** [comment]
Только что проверил на своём инстансе без `extension` - отработало без ошибок. И на инстансе Артёма попробовал, тоже все работает. Как ошибку воспроизвести?

**Comment by trolleway** [comment]
Разгадали работающий образец вызова:

```
import requests
import json

req = requests.put('http://trolleway.nextgis.com/api/resource/53/feature/12', data=json.dumps({ "fields": {"line_id": 1, "name": ""}}) , auth=('debugger','debugger'))
print 'status code:'+str(req)
```
