### ISSUE TITLE
raster upload failed with error:  "Errors found during data validation on server. Correct error and try again. Error message:  GDAL library was unable to open the file."

### ISSUE THREAD

**Issue by p-climate** [nextgis/nextgis.com-webgis#20]
Upload raster SRTM tile fails with GDAL error. 
STEPS:
1. login to webgis as admin
2. create resource/raster layer   http://mujigae400.nextgis.com/resource/0/create?cls=raster_layer
3. CRS = EPSG:3857
4. file is RGB .tif 
5. Create resource fails with message: "Errors found during data validation on server. Correct error and try again. Error message:  GDAL library was unable to open the file."

-->  tried both .tif unzipped and zipped. 
See attachment
[n21_e110_1arc_v3_TIF.zip](https://github.com/nextgis/nextgis.com-webgis/files/427836/n21_e110_1arc_v3_TIF.zip)

**Comment by BishopGIS** [comment]
Your raster has only 1 band, 3 or 4 are required (see. http://docs.nextgis.com/docs_ngweb/source/layers.html#raster-layer)

```
$ gdalinfo n21_e110_1arc_v3.tif 
Driver: GTiff/GeoTIFF
Files: n21_e110_1arc_v3.tif
Size is 3601, 3601
Coordinate System is:
PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH],
    EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"],
    AUTHORITY["EPSG","3857"]]
Origin = (12245128.526219701394439,2511541.910123094916344)
Pixel Size = (30.922080775913731,-33.235180001967358)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (12245128.526, 2511541.910) (109d59'59.50"E, 22d 0' 0.50"N)
Lower Left  (12245128.526, 2391862.027) (109d59'59.50"E, 20d59'59.50"N)
Upper Right (12356478.939, 2511541.910) (111d 0' 0.50"E, 22d 0' 0.50"N)
Lower Right (12356478.939, 2391862.027) (111d 0' 0.50"E, 20d59'59.50"N)
Center      (12300803.733, 2451701.969) (110d30' 0.00"E, 21d30' 3.10"N)
Band 1 Block=3601x1 Type=Int16, ColorInterp=Gray
  NoData Value=-32767
```

To get compatible raster you can create it in QGIS like follow:
1. Open raster in QGIS
2. Select render type "Singelband pseudocolor"
3. Save as selecting output mode "rendered image"

![2016-08-20 00-28-15](https://cloud.githubusercontent.com/assets/1708122/17824897/baa3469c-6675-11e6-8616-fa48da26a12a.png)
![2016-08-20 00-28-31](https://cloud.githubusercontent.com/assets/1708122/17824898/baa3d148-6675-11e6-8714-86c67f155f86.png)

Also you can use NextGIS connect plugin: https://plugins.qgis.org/plugins/nextgis_connect/

**Comment by p-climate** [comment]
Димитрий:

That worked.

I have created several raster resources for this project:
http://mujigae400.nextgis.com/resource/1/display

Now I am trying to create a raster and getting the message:  "Could not 
load file! Try again"

The file size is 1.01GB.  Is there a size limit on file upload?

Here is the raster file on dropbox:
https://www.dropbox.com/s/kve8iwi8xyzcx5a/SRTM_Guangxi_mosaic_IMAGE.tif?dl=0

Большое спасибо.

```
 Peter Kokopeli
 CIO
 240-271-2434 c

 peter.kokopeli@climatedecision.net
 http://climatedecision.net/
```

------ Original Message ------

**Comment by simgislab** [comment]
Yes, there is a limit. 
You can't upload files bigger than 500Mb on free plan

**Comment by p-climate** [comment]
Maxim:

Can you provide more information on your commercial plans?

Sincerely,

```
 Peter Kokopeli
 CIO
 240-271-2434 c

 peter.kokopeli@climatedecision.net
 http://climatedecision.net/
```

------ Original Message ------

**Comment by simgislab** [comment]
some information can be found here: http://nextgis.com/nextgis-com
expected price will be around 50$/mo
we're finalizing details at the moment

**Comment by p-climate** [comment]
Maxim:

http://mujigae400.nextgis.com/resource/1/display

We are interested in developing the site above to automate:
1. user upload of CSV point file
2. perform operations (interpolation, raster calculation) to find 
   inundation depth
3. display inundation results.

Does NextGIS also offer development services of this type?

Sincerely,

```
 Peter Kokopeli
 CIO
 240-271-2434 c

 peter.kokopeli@climatedecision.net
 http://climatedecision.net/
```

------ Original Message ------
