### ISSUE TITLE
Not all strings in web map translated 

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis.com-webgis#22]
![2016-08-30 21-54-41](https://cloud.githubusercontent.com/assets/1708122/18102890/5dbd4f20-6f05-11e6-91c1-2d0d509a0e36.png)

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/277de19812521593282e7c03bb8eb26dd74fd455
