### ISSUE TITLE
Wrong postion for vector layer on low zoom

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis.com-webgis#24]
URL: http://rasinari.nextgis.com/resource/18/display

![2016-09-09 10-55-05](https://cloud.githubusercontent.com/assets/1708122/18379585/5d6ca314-7684-11e6-9e9e-33996225d36e.png)

![2016-09-09 10-55-21](https://cloud.githubusercontent.com/assets/1708122/18379586/5d6fa8c0-7684-11e6-81c3-a79fb0a8390d.png)

![2016-09-09 10-55-32](https://cloud.githubusercontent.com/assets/1708122/18379587/5d72ffc0-7684-11e6-9104-677129c6392e.png)

**Comment by kalenkov** [comment]
I reported similar bug some time ago https://github.com/nextgis/nextgis.com-webgis/issues/17

**Comment by simgislab** [comment]
are screenshots identical? it's not clear what they are supposed to mean

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb_qgis/commit/077b7e799478f4c059049230fa8421882a7b06c8
