### ISSUE TITLE
Не могу добавить векторный слой: недостаточно прав

### ISSUE THREAD

**Issue by OnkelTem** [nextgis/nextgis.com-webgis#35]
Добавляю векторный слой, выбираю geo-json с компа, нажимаю Создать и получаю сообщение "Недостаточно прав". 

GeoJson брал отсюда: https://github.com/johan/world.geo.json/blob/master/countries.geo.json

**Comment by BishopGIS** [comment]
В административном интерфейсе авторизовывались?
Справа вверху отображается ваш логин?

**Comment by OnkelTem** [comment]
> В административном интерфейсе авторизовывались? 
> Справа вверху отображается ваш логин?

Ой, действительно, не отображается, там просто "войти".
И когда я нажимаю, появляется форма с логином. Но... откуда я возьму данные для логина?

**Comment by BishopGIS** [comment]
При создании веб ГИС на почту должно было придти письмо с этой информацией. Если 
 письмо потерялось, то пароль можно сменить в http://my.nextgis.com

**Comment by OnkelTem** [comment]
Спасибо, я изменил пароль. Но какой логин?

И еще: не лучше ли добавить эту информацию где-нибудь в системе на странице? Типа: вы не авторизованный пользователь, для авторизации нажмите сюда. И когда появляется форма логина на ней написать: получить **логин и пароль** вы можете нажав вот сюда... М-м?

**Comment by OnkelTem** [comment]
Кроме того, вы сами посудите насколько логично устроено сейчас.

1. Я захожу на сайт nextgis
2. Жму войти
3. Логинюсь!!! (через гугл)
4. Попадаю на страницу, где вижу: `The address of your Web GIS — onkeltem.nextgis.com`
5. Перехожу по ссылке
6. Нажимаю "добавить векторный слой" и т.д...

Короче, где я должен догадаться, что, как бы залогинившись, я как бы не залогинен?

**Comment by drnextgis** [comment]
Вам вот такое письмо на почту не приходило? То есть логин **administrator**:

```
Ваша Веб ГИС готова к использованию!

Информация для входа:
  Имя: administrator
  Пароль: *
  URL: http://*.nextgis.com

Команда NextGIS
```

**Comment by OnkelTem** [comment]
Может и было письмо год назад, когда, я зарегился и, не разобравшись что к чему, бросил это занятие. Сейчас вот решил снова попробовать, так как вы напомнили о себе письмом "`Новости nextgis.com #6`" :)

Кстати, а зачем мне видеть таблицу с правами на главной странице системы? Тем более, что я не понимаю что они означают, особенно двойная кодировка - цветами и буквами (А, Е и т.д., на которые когда наводишь мышой ничего не показывается).

**Comment by drnextgis** [comment]
В итоге то удалось войти?

**Comment by OnkelTem** [comment]
> В итоге то удалось войти?

Да, зашел, спасибо!

Теперь проблемы с самим уже Json-ом :)  Неверный тип геометрии или типа того. Вообще, не дело конечно в этом тикете продолжать, сейчас поищу другие, может уже обсуждалось.

**Comment by simgislab** [comment]
за обратную связь спасибо, постепенно все будем упрощать и улучшать. Замечания предложения лучше отдельными тикетами.
