### ISSUE TITLE
Как сделать прозрачным векторный слой?

### ISSUE THREAD

**Issue by OnkelTem** [nextgis/nextgis.com-webgis#36]
Не вижу в документации в стилях mapserver этого.

**Comment by drnextgis** [comment]
При настройке карты на вкладке, где вы задаёте отображаемое имя слоя, есть свойство "Прозрачность" (0 - 100). Можно и в MapServer:

```xml
<style>
  <opacity>50</opacity>
  ...
</style>
```

**Comment by OnkelTem** [comment]
Класс, спасибо. Я когда документацию просматривал, поиском по странице старательно искал opacity (или transp, не помню уже). Либо криво искал, либо не нашел.
