### ISSUE TITLE
Как можно просматривать карту? Можно ли экспортировать?

### ISSUE THREAD

**Issue by OnkelTem** [nextgis/nextgis.com-webgis#37]
Если я создам карту, как потом другие пользователи смогут просматривать мои данные?
Например, чтобы можно было подставлять разные карты - гугл, яндекс и тд? OSM по-умолчанию уже как бы есть.
И можно ли экспортировать данные в другие системы, чтобы подсасывать geojson например отсюда?

**Comment by drnextgis** [comment]
* Как добавлять подложки описано [тут](http://docs.nextgis.ru/docs_ngcom/source/data_connect.html#ngcom-basemap-layer).
* Экспортировать можно - есть кнопка в интерфейсе "Загрузить GeoJSON", [пример](http://rykovd.nextgis.com/api/resource/322/geojson).
* REST API [задокументировано](http://docs.nextgis.ru/docs_ngweb_dev/doc/developer/toc.html).
* Если нужен CORS, то [вот](http://docs.nextgis.ru/docs_ngcom/source/CORS.html).

**Comment by OnkelTem** [comment]
В общем, всё сложно, я понял :)
Спасибо.

P.S. Правда, спасибо.
