### ISSUE TITLE
Не получается загрузить векторный слой в Веб ГИС

### ISSUE THREAD

**Issue by ngc-2244** [nextgis/nextgis.com-webgis#43]
Добрый день!

Выводит сообщение с ошибкой 
"422 — Ошибка валидации
Библиотеке GDAL не удалось открыть файл."
Что это значит? И что нужно сделать, чтобы удалось загрузить?

**Comment by ngc-2244** [comment]
Уже получилось

**Comment by simgislab** [comment]
для начала показать что грузите
