### ISSUE TITLE
 This XML file does not appear to have any style information associated with it

### ISSUE THREAD

**Issue by bagration26** [nextgis/nextgis.com-webgis#6]
Здравствуйте, создаю wfs сервис и выдает ошибку This XML file does not appear to have any style information associated with it. The document tree is shown below. <ExceptionReport xmlns="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 owsExceptionReport.xsd" version="1.0.0" xml:lang="en"> <Exception exceptionCode="" locator="" layer=""> <ExceptionText>Can't find layer 'None'</ExceptionText> <ExceptionDump/> </Exception> </ExceptionReport>

**Comment by simgislab** [comment]
слои в WFS добавили?

**Comment by bagration26** [comment]
да

**Comment by simgislab** [comment]
опишите полную последовательность действий, приведите ссылку на свою Веб ГИС

**Comment by bagration26** [comment]
Ресурсы - Сервис WFS - ресурс - задал имя - сервис wfs - добавить слой- ключ 
http://rpz1.nextgis.com/resource/0

**Comment by BishopGIS** [comment]
В NextGIS QGIS WFS работает. В каком ПО выводится такая ошибка?
![2016-06-03 00-20-19](https://cloud.githubusercontent.com/assets/1708122/15761462/6f3515a2-2929-11e6-82d3-423e2a1e8878.png)

**Comment by bagration26** [comment]
в гугл хром, я просто по ссилке переходил..., с NextGIS QGIS все нормально, а как подлючить мобильное приложение?

**Comment by simgislab** [comment]
просто переходить по ссылке не нужно, ссылка на WFS сервис должна открываться в клиенте, который понимает этот протокол. Веб браузер к этим клиентам не относится. Для мобильного эта ссылка тоже не нужна.

Работа с Веб ГИС через мобильный клиент описана здесь: http://docs.nextgis.ru/docs_ngmobile/source/ngw_integration.html

**Comment by bagration26** [comment]
все настроил, у Веб ГИС не отображаются изменения сделанные в моб. приложении, синхронизацию настроил правильно..

**Comment by simgislab** [comment]
вы слишком лаконичны, нет версии мобильного приложения, нет информации какой слой вы синхронизирует. Если вы хотите, чтобы вам помогли, приведите четкую ПОСЛЕДОВАТЕЛЬНОСТЬ шагов.

**Comment by BishopGIS** [comment]
Если версия мобильного из маркета, просьба прверить на предрелизной версии: https://tsfr.io/804gdm
URL адрес надо набирать в браузере мобильного устройства, иначе будет выдано предупреждение, что устройство не поддерживается.

**Comment by bagration26** [comment]
версия приложения 2.3, 1) Создал подключения к NextGIS Web (“Настройки” -NextGIS Web -Настройки NextGIS Web - Добавить учетную запись - ввел параметры подключения - подключился) 2) вызвал меню опций - Добавить слой - выбрал "add from NGW" -  Выбрал из списка учетную запись - выбрал векторный слой "ozera" - добавил. 3) меню опций  - настройки - NextGIS Web/ Настройки NextGIS Web - зашел в учетною запись - поставил птичку синхронизация автоматическая и на против слоя, интервал 5 мин. существующие элементы слоя отображаются в приложении, после редактирование на NextGIS Web не отображаются внесенные правки

**Comment by simgislab** [comment]
спасибо, так гораздо лучше!
Вам действительно нужно либо:

> просьба прверить на предрелизной версии: https://tsfr.io/804gdm

либо дождаться релиза 2.4 который будет на следующей неделе.

**Comment by bagration26** [comment]
на предрелизной версии  все ОК, спасибо
